name: Website Validation

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check HTML File Exists
        run: ls

      - name: Validate Website
        run: |
          echo "Website validation successful"
          cat index.html
